### ISSUE TITLE
Dockerc image not available

### ISSUE THREAD

**Issue by jimaldon** [arpan-kusari/Naturalistic-SUMO-Gym#1]
The repo's About as well as the paper mention that the python package is available as a docker container however I don't see a Dockerfile or a link to an image on the docker hub? Is it still in development?

**Comment by arpan-kusari** [comment]
We needed to roll that version back because there are problems with docker and SUMO. It is in development and we will release it soon.

**Comment by arpan-kusari** [comment]
Hi, just wanted to provide an update that we have released the docker image. Please let us know if there are any issues.
